//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandAlonePackingLib.SAPFuncs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="SAPFuncs.ZStandalonePacking")]
    public interface ZStandalonePacking {
        
        // CODEGEN: Generating message contract since the operation ZChangeUserPassword is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordResponse1 ZChangeUserPassword(StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordResponse1> ZChangeUserPasswordAsync(StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation ZGetDgaUsers is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StandAlonePackingLib.SAPFuncs.ZGetDgaUsersResponse1 ZGetDgaUsers(StandAlonePackingLib.SAPFuncs.ZGetDgaUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZGetDgaUsersResponse1> ZGetDgaUsersAsync(StandAlonePackingLib.SAPFuncs.ZGetDgaUsersRequest request);
        
        // CODEGEN: Generating message contract since the operation ZGetFinishedGoodMaterials is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsResponse1 ZGetFinishedGoodMaterials(StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsResponse1> ZGetFinishedGoodMaterialsAsync(StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsRequest request);
        
        // CODEGEN: Generating message contract since the operation ZGetProductionOrders is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersResponse1 ZGetProductionOrders(StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersResponse1> ZGetProductionOrdersAsync(StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersRequest request);
        
        // CODEGEN: Generating message contract since the operation ZGetSystemInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StandAlonePackingLib.SAPFuncs.ZGetSystemInfoResponse1 ZGetSystemInfo(StandAlonePackingLib.SAPFuncs.ZGetSystemInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZGetSystemInfoResponse1> ZGetSystemInfoAsync(StandAlonePackingLib.SAPFuncs.ZGetSystemInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation ZReceiptCartons is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StandAlonePackingLib.SAPFuncs.ZReceiptCartonsResponse1 ZReceiptCartons(StandAlonePackingLib.SAPFuncs.ZReceiptCartonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZReceiptCartonsResponse1> ZReceiptCartonsAsync(StandAlonePackingLib.SAPFuncs.ZReceiptCartonsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZChangeUserPassword : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dgaUserField;
        
        private string newPasswordField;
        
        private string plantField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DgaUser {
            get {
                return this.dgaUserField;
            }
            set {
                this.dgaUserField = value;
                this.RaisePropertyChanged("DgaUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NewPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
                this.RaisePropertyChanged("NewPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
                this.RaisePropertyChanged("Plant");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsapaCartonRet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serialField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsapaCarton : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serialField;
        
        private string materialNumField;
        
        private string batchField;
        
        private string orderNumField;
        
        private string plantField;
        
        private string storageLctnField;
        
        private decimal packedQtyField;
        
        private string packedUomField;
        
        private decimal weightField;
        
        private decimal plannedWeightField;
        
        private decimal actualWeightField;
        
        private decimal tareWeightField;
        
        private string packedOnField;
        
        private string packedAtField;
        
        private string manuDateField;
        
        private string expiryDateField;
        
        private string deviceField;
        
        private string partCartonField;
        
        private string grReversalField;
        
        private string eagleBarcodeField;
        
        private string useFreezerField;
        
        private decimal actualClField;
        
        private string dgaUserField;
        
        private string slaughterDatesField;
        
        private string reworkIssueField;
        
        private string prtCrtBarcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MaterialNum {
            get {
                return this.materialNumField;
            }
            set {
                this.materialNumField = value;
                this.RaisePropertyChanged("MaterialNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
                this.RaisePropertyChanged("Batch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string OrderNum {
            get {
                return this.orderNumField;
            }
            set {
                this.orderNumField = value;
                this.RaisePropertyChanged("OrderNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
                this.RaisePropertyChanged("Plant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string StorageLctn {
            get {
                return this.storageLctnField;
            }
            set {
                this.storageLctnField = value;
                this.RaisePropertyChanged("StorageLctn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal PackedQty {
            get {
                return this.packedQtyField;
            }
            set {
                this.packedQtyField = value;
                this.RaisePropertyChanged("PackedQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PackedUom {
            get {
                return this.packedUomField;
            }
            set {
                this.packedUomField = value;
                this.RaisePropertyChanged("PackedUom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal PlannedWeight {
            get {
                return this.plannedWeightField;
            }
            set {
                this.plannedWeightField = value;
                this.RaisePropertyChanged("PlannedWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal ActualWeight {
            get {
                return this.actualWeightField;
            }
            set {
                this.actualWeightField = value;
                this.RaisePropertyChanged("ActualWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal TareWeight {
            get {
                return this.tareWeightField;
            }
            set {
                this.tareWeightField = value;
                this.RaisePropertyChanged("TareWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string PackedOn {
            get {
                return this.packedOnField;
            }
            set {
                this.packedOnField = value;
                this.RaisePropertyChanged("PackedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string PackedAt {
            get {
                return this.packedAtField;
            }
            set {
                this.packedAtField = value;
                this.RaisePropertyChanged("PackedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ManuDate {
            get {
                return this.manuDateField;
            }
            set {
                this.manuDateField = value;
                this.RaisePropertyChanged("ManuDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("ExpiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
                this.RaisePropertyChanged("Device");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string PartCarton {
            get {
                return this.partCartonField;
            }
            set {
                this.partCartonField = value;
                this.RaisePropertyChanged("PartCarton");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string GrReversal {
            get {
                return this.grReversalField;
            }
            set {
                this.grReversalField = value;
                this.RaisePropertyChanged("GrReversal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string EagleBarcode {
            get {
                return this.eagleBarcodeField;
            }
            set {
                this.eagleBarcodeField = value;
                this.RaisePropertyChanged("EagleBarcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string UseFreezer {
            get {
                return this.useFreezerField;
            }
            set {
                this.useFreezerField = value;
                this.RaisePropertyChanged("UseFreezer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public decimal ActualCl {
            get {
                return this.actualClField;
            }
            set {
                this.actualClField = value;
                this.RaisePropertyChanged("ActualCl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string DgaUser {
            get {
                return this.dgaUserField;
            }
            set {
                this.dgaUserField = value;
                this.RaisePropertyChanged("DgaUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string SlaughterDates {
            get {
                return this.slaughterDatesField;
            }
            set {
                this.slaughterDatesField = value;
                this.RaisePropertyChanged("SlaughterDates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string ReworkIssue {
            get {
                return this.reworkIssueField;
            }
            set {
                this.reworkIssueField = value;
                this.RaisePropertyChanged("ReworkIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string PrtCrtBarcode {
            get {
                return this.prtCrtBarcodeField;
            }
            set {
                this.prtCrtBarcodeField = value;
                this.RaisePropertyChanged("PrtCrtBarcode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsapaProdDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string manuDateField;
        
        private string slaughterDatesField;
        
        private string defaultValField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ManuDate {
            get {
                return this.manuDateField;
            }
            set {
                this.manuDateField = value;
                this.RaisePropertyChanged("ManuDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SlaughterDates {
            get {
                return this.slaughterDatesField;
            }
            set {
                this.slaughterDatesField = value;
                this.RaisePropertyChanged("SlaughterDates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DefaultVal {
            get {
                return this.defaultValField;
            }
            set {
                this.defaultValField = value;
                this.RaisePropertyChanged("DefaultVal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsapaProdOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderNumField;
        
        private string materialNumField;
        
        private decimal targetQtyField;
        
        private decimal packedQtyField;
        
        private string uomField;
        
        private decimal tareWeightField;
        
        private string orderTypeField;
        
        private string plantField;
        
        private string storageLctnField;
        
        private string unlimOverdelField;
        
        private decimal overdelPercField;
        
        private string salesDocField;
        
        private string customerField;
        
        private string custNameField;
        
        private string startDateField;
        
        private System.DateTime startTimeField;
        
        private string useFreezerField;
        
        private string stkTypeField;
        
        private string seqNumField;
        
        private string relIndField;
        
        private string delIndField;
        
        private decimal bomBaseQtyField;
        
        private string bomBaseUomField;
        
        private string slaughterDatesField;
        
        private string delivDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrderNum {
            get {
                return this.orderNumField;
            }
            set {
                this.orderNumField = value;
                this.RaisePropertyChanged("OrderNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MaterialNum {
            get {
                return this.materialNumField;
            }
            set {
                this.materialNumField = value;
                this.RaisePropertyChanged("MaterialNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal TargetQty {
            get {
                return this.targetQtyField;
            }
            set {
                this.targetQtyField = value;
                this.RaisePropertyChanged("TargetQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal PackedQty {
            get {
                return this.packedQtyField;
            }
            set {
                this.packedQtyField = value;
                this.RaisePropertyChanged("PackedQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
                this.RaisePropertyChanged("Uom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal TareWeight {
            get {
                return this.tareWeightField;
            }
            set {
                this.tareWeightField = value;
                this.RaisePropertyChanged("TareWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("OrderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
                this.RaisePropertyChanged("Plant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string StorageLctn {
            get {
                return this.storageLctnField;
            }
            set {
                this.storageLctnField = value;
                this.RaisePropertyChanged("StorageLctn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string UnlimOverdel {
            get {
                return this.unlimOverdelField;
            }
            set {
                this.unlimOverdelField = value;
                this.RaisePropertyChanged("UnlimOverdel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal OverdelPerc {
            get {
                return this.overdelPercField;
            }
            set {
                this.overdelPercField = value;
                this.RaisePropertyChanged("OverdelPerc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string SalesDoc {
            get {
                return this.salesDocField;
            }
            set {
                this.salesDocField = value;
                this.RaisePropertyChanged("SalesDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string CustName {
            get {
                return this.custNameField;
            }
            set {
                this.custNameField = value;
                this.RaisePropertyChanged("CustName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=15)]
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string UseFreezer {
            get {
                return this.useFreezerField;
            }
            set {
                this.useFreezerField = value;
                this.RaisePropertyChanged("UseFreezer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string StkType {
            get {
                return this.stkTypeField;
            }
            set {
                this.stkTypeField = value;
                this.RaisePropertyChanged("StkType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string SeqNum {
            get {
                return this.seqNumField;
            }
            set {
                this.seqNumField = value;
                this.RaisePropertyChanged("SeqNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string RelInd {
            get {
                return this.relIndField;
            }
            set {
                this.relIndField = value;
                this.RaisePropertyChanged("RelInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string DelInd {
            get {
                return this.delIndField;
            }
            set {
                this.delIndField = value;
                this.RaisePropertyChanged("DelInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public decimal BomBaseQty {
            get {
                return this.bomBaseQtyField;
            }
            set {
                this.bomBaseQtyField = value;
                this.RaisePropertyChanged("BomBaseQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string BomBaseUom {
            get {
                return this.bomBaseUomField;
            }
            set {
                this.bomBaseUomField = value;
                this.RaisePropertyChanged("BomBaseUom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string SlaughterDates {
            get {
                return this.slaughterDatesField;
            }
            set {
                this.slaughterDatesField = value;
                this.RaisePropertyChanged("SlaughterDates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string DelivDate {
            get {
                return this.delivDateField;
            }
            set {
                this.delivDateField = value;
                this.RaisePropertyChanged("DelivDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsapaFinGoodMat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string matNumberField;
        
        private string descriptionField;
        
        private string labelLine1Field;
        
        private string labelLine2Field;
        
        private string labelLine3Field;
        
        private string labelLine4Field;
        
        private string labelLine5Field;
        
        private string fixedWeightField;
        
        private decimal maxWeightField;
        
        private decimal minWeightField;
        
        private decimal nomWeightField;
        
        private string wghtUomField;
        
        private string baseUomField;
        
        private string parallelUomField;
        
        private string unlimOverdelField;
        
        private decimal overdelPercField;
        
        private string eanField;
        
        private string madeToOrdField;
        
        private string labelFileField;
        
        private decimal shelfLifeField;
        
        private string custMatNumField;
        
        private string oldMatNumField;
        
        private string targetMatNumField;
        
        private string woolGrpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MatNumber {
            get {
                return this.matNumberField;
            }
            set {
                this.matNumberField = value;
                this.RaisePropertyChanged("MatNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LabelLine1 {
            get {
                return this.labelLine1Field;
            }
            set {
                this.labelLine1Field = value;
                this.RaisePropertyChanged("LabelLine1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LabelLine2 {
            get {
                return this.labelLine2Field;
            }
            set {
                this.labelLine2Field = value;
                this.RaisePropertyChanged("LabelLine2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LabelLine3 {
            get {
                return this.labelLine3Field;
            }
            set {
                this.labelLine3Field = value;
                this.RaisePropertyChanged("LabelLine3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LabelLine4 {
            get {
                return this.labelLine4Field;
            }
            set {
                this.labelLine4Field = value;
                this.RaisePropertyChanged("LabelLine4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string LabelLine5 {
            get {
                return this.labelLine5Field;
            }
            set {
                this.labelLine5Field = value;
                this.RaisePropertyChanged("LabelLine5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FixedWeight {
            get {
                return this.fixedWeightField;
            }
            set {
                this.fixedWeightField = value;
                this.RaisePropertyChanged("FixedWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal MaxWeight {
            get {
                return this.maxWeightField;
            }
            set {
                this.maxWeightField = value;
                this.RaisePropertyChanged("MaxWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal MinWeight {
            get {
                return this.minWeightField;
            }
            set {
                this.minWeightField = value;
                this.RaisePropertyChanged("MinWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal NomWeight {
            get {
                return this.nomWeightField;
            }
            set {
                this.nomWeightField = value;
                this.RaisePropertyChanged("NomWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string WghtUom {
            get {
                return this.wghtUomField;
            }
            set {
                this.wghtUomField = value;
                this.RaisePropertyChanged("WghtUom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string BaseUom {
            get {
                return this.baseUomField;
            }
            set {
                this.baseUomField = value;
                this.RaisePropertyChanged("BaseUom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ParallelUom {
            get {
                return this.parallelUomField;
            }
            set {
                this.parallelUomField = value;
                this.RaisePropertyChanged("ParallelUom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string UnlimOverdel {
            get {
                return this.unlimOverdelField;
            }
            set {
                this.unlimOverdelField = value;
                this.RaisePropertyChanged("UnlimOverdel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal OverdelPerc {
            get {
                return this.overdelPercField;
            }
            set {
                this.overdelPercField = value;
                this.RaisePropertyChanged("OverdelPerc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Ean {
            get {
                return this.eanField;
            }
            set {
                this.eanField = value;
                this.RaisePropertyChanged("Ean");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string MadeToOrd {
            get {
                return this.madeToOrdField;
            }
            set {
                this.madeToOrdField = value;
                this.RaisePropertyChanged("MadeToOrd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string LabelFile {
            get {
                return this.labelFileField;
            }
            set {
                this.labelFileField = value;
                this.RaisePropertyChanged("LabelFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public decimal ShelfLife {
            get {
                return this.shelfLifeField;
            }
            set {
                this.shelfLifeField = value;
                this.RaisePropertyChanged("ShelfLife");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string CustMatNum {
            get {
                return this.custMatNumField;
            }
            set {
                this.custMatNumField = value;
                this.RaisePropertyChanged("CustMatNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string OldMatNum {
            get {
                return this.oldMatNumField;
            }
            set {
                this.oldMatNumField = value;
                this.RaisePropertyChanged("OldMatNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string TargetMatNum {
            get {
                return this.targetMatNumField;
            }
            set {
                this.targetMatNumField = value;
                this.RaisePropertyChanged("TargetMatNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string WoolGrp {
            get {
                return this.woolGrpField;
            }
            set {
                this.woolGrpField = value;
                this.RaisePropertyChanged("WoolGrp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsapaUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dgaUserField;
        
        private string nameField;
        
        private string passwordField;
        
        private string activeField;
        
        private string chgPasswordField;
        
        private byte failedLogonsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DgaUser {
            get {
                return this.dgaUserField;
            }
            set {
                this.dgaUserField = value;
                this.RaisePropertyChanged("DgaUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ChgPassword {
            get {
                return this.chgPasswordField;
            }
            set {
                this.chgPasswordField = value;
                this.RaisePropertyChanged("ChgPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public byte FailedLogons {
            get {
                return this.failedLogonsField;
            }
            set {
                this.failedLogonsField = value;
                this.RaisePropertyChanged("FailedLogons");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZChangeUserPasswordResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZChangeUserPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public StandAlonePackingLib.SAPFuncs.ZChangeUserPassword ZChangeUserPassword;
        
        public ZChangeUserPasswordRequest() {
        }
        
        public ZChangeUserPasswordRequest(StandAlonePackingLib.SAPFuncs.ZChangeUserPassword ZChangeUserPassword) {
            this.ZChangeUserPassword = ZChangeUserPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZChangeUserPasswordResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordResponse ZChangeUserPasswordResponse;
        
        public ZChangeUserPasswordResponse1() {
        }
        
        public ZChangeUserPasswordResponse1(StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordResponse ZChangeUserPasswordResponse) {
            this.ZChangeUserPasswordResponse = ZChangeUserPasswordResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZGetDgaUsers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
                this.RaisePropertyChanged("Device");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZGetDgaUsersResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZsapaUser[] usersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZsapaUser[] Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
                this.RaisePropertyChanged("Users");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZGetDgaUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public StandAlonePackingLib.SAPFuncs.ZGetDgaUsers ZGetDgaUsers;
        
        public ZGetDgaUsersRequest() {
        }
        
        public ZGetDgaUsersRequest(StandAlonePackingLib.SAPFuncs.ZGetDgaUsers ZGetDgaUsers) {
            this.ZGetDgaUsers = ZGetDgaUsers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZGetDgaUsersResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public StandAlonePackingLib.SAPFuncs.ZGetDgaUsersResponse ZGetDgaUsersResponse;
        
        public ZGetDgaUsersResponse1() {
        }
        
        public ZGetDgaUsersResponse1(StandAlonePackingLib.SAPFuncs.ZGetDgaUsersResponse ZGetDgaUsersResponse) {
            this.ZGetDgaUsersResponse = ZGetDgaUsersResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZGetFinishedGoodMaterials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deviceField;
        
        private string lastSyncDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
                this.RaisePropertyChanged("Device");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LastSyncDate {
            get {
                return this.lastSyncDateField;
            }
            set {
                this.lastSyncDateField = value;
                this.RaisePropertyChanged("LastSyncDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZGetFinishedGoodMaterialsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZsapaFinGoodMat[] finGoodsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZsapaFinGoodMat[] FinGoods {
            get {
                return this.finGoodsField;
            }
            set {
                this.finGoodsField = value;
                this.RaisePropertyChanged("FinGoods");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZGetFinishedGoodMaterialsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterials ZGetFinishedGoodMaterials;
        
        public ZGetFinishedGoodMaterialsRequest() {
        }
        
        public ZGetFinishedGoodMaterialsRequest(StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterials ZGetFinishedGoodMaterials) {
            this.ZGetFinishedGoodMaterials = ZGetFinishedGoodMaterials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZGetFinishedGoodMaterialsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsResponse ZGetFinishedGoodMaterialsResponse;
        
        public ZGetFinishedGoodMaterialsResponse1() {
        }
        
        public ZGetFinishedGoodMaterialsResponse1(StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsResponse ZGetFinishedGoodMaterialsResponse) {
            this.ZGetFinishedGoodMaterialsResponse = ZGetFinishedGoodMaterialsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZGetProductionOrders : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private string deviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
                this.RaisePropertyChanged("Device");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZGetProductionOrdersResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZsapaProdOrder[] ordersField;
        
        private ZsapaProdDate[] prodDatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZsapaProdOrder[] Orders {
            get {
                return this.ordersField;
            }
            set {
                this.ordersField = value;
                this.RaisePropertyChanged("Orders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZsapaProdDate[] ProdDates {
            get {
                return this.prodDatesField;
            }
            set {
                this.prodDatesField = value;
                this.RaisePropertyChanged("ProdDates");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZGetProductionOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public StandAlonePackingLib.SAPFuncs.ZGetProductionOrders ZGetProductionOrders;
        
        public ZGetProductionOrdersRequest() {
        }
        
        public ZGetProductionOrdersRequest(StandAlonePackingLib.SAPFuncs.ZGetProductionOrders ZGetProductionOrders) {
            this.ZGetProductionOrders = ZGetProductionOrders;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZGetProductionOrdersResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersResponse ZGetProductionOrdersResponse;
        
        public ZGetProductionOrdersResponse1() {
        }
        
        public ZGetProductionOrdersResponse1(StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersResponse ZGetProductionOrdersResponse) {
            this.ZGetProductionOrdersResponse = ZGetProductionOrdersResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZGetSystemInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZGetSystemInfoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appServerField;
        
        private string clientField;
        
        private string dateField;
        
        private string hostNameField;
        
        private string systemIdField;
        
        private System.DateTime timeField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AppServer {
            get {
                return this.appServerField;
            }
            set {
                this.appServerField = value;
                this.RaisePropertyChanged("AppServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("Client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string HostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
                this.RaisePropertyChanged("HostName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SystemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
                this.RaisePropertyChanged("SystemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=5)]
        public System.DateTime Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZGetSystemInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public StandAlonePackingLib.SAPFuncs.ZGetSystemInfo ZGetSystemInfo;
        
        public ZGetSystemInfoRequest() {
        }
        
        public ZGetSystemInfoRequest(StandAlonePackingLib.SAPFuncs.ZGetSystemInfo ZGetSystemInfo) {
            this.ZGetSystemInfo = ZGetSystemInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZGetSystemInfoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public StandAlonePackingLib.SAPFuncs.ZGetSystemInfoResponse ZGetSystemInfoResponse;
        
        public ZGetSystemInfoResponse1() {
        }
        
        public ZGetSystemInfoResponse1(StandAlonePackingLib.SAPFuncs.ZGetSystemInfoResponse ZGetSystemInfoResponse) {
            this.ZGetSystemInfoResponse = ZGetSystemInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZReceiptCartons : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZsapaCarton[] cartonsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZsapaCarton[] Cartons {
            get {
                return this.cartonsField;
            }
            set {
                this.cartonsField = value;
                this.RaisePropertyChanged("Cartons");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZReceiptCartonsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZsapaCartonRet[] returnMsgsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZsapaCartonRet[] ReturnMsgs {
            get {
                return this.returnMsgsField;
            }
            set {
                this.returnMsgsField = value;
                this.RaisePropertyChanged("ReturnMsgs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZReceiptCartonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public StandAlonePackingLib.SAPFuncs.ZReceiptCartons ZReceiptCartons;
        
        public ZReceiptCartonsRequest() {
        }
        
        public ZReceiptCartonsRequest(StandAlonePackingLib.SAPFuncs.ZReceiptCartons ZReceiptCartons) {
            this.ZReceiptCartons = ZReceiptCartons;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZReceiptCartonsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public StandAlonePackingLib.SAPFuncs.ZReceiptCartonsResponse ZReceiptCartonsResponse;
        
        public ZReceiptCartonsResponse1() {
        }
        
        public ZReceiptCartonsResponse1(StandAlonePackingLib.SAPFuncs.ZReceiptCartonsResponse ZReceiptCartonsResponse) {
            this.ZReceiptCartonsResponse = ZReceiptCartonsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZStandalonePackingChannel : StandAlonePackingLib.SAPFuncs.ZStandalonePacking, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZStandalonePackingClient : System.ServiceModel.ClientBase<StandAlonePackingLib.SAPFuncs.ZStandalonePacking>, StandAlonePackingLib.SAPFuncs.ZStandalonePacking {
        
        public ZStandalonePackingClient() {
        }
        
        public ZStandalonePackingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZStandalonePackingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZStandalonePackingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZStandalonePackingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordResponse1 StandAlonePackingLib.SAPFuncs.ZStandalonePacking.ZChangeUserPassword(StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordRequest request) {
            return base.Channel.ZChangeUserPassword(request);
        }
        
        public StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordResponse ZChangeUserPassword(StandAlonePackingLib.SAPFuncs.ZChangeUserPassword ZChangeUserPassword1) {
            StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordRequest inValue = new StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordRequest();
            inValue.ZChangeUserPassword = ZChangeUserPassword1;
            StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordResponse1 retVal = ((StandAlonePackingLib.SAPFuncs.ZStandalonePacking)(this)).ZChangeUserPassword(inValue);
            return retVal.ZChangeUserPasswordResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordResponse1> StandAlonePackingLib.SAPFuncs.ZStandalonePacking.ZChangeUserPasswordAsync(StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordRequest request) {
            return base.Channel.ZChangeUserPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordResponse1> ZChangeUserPasswordAsync(StandAlonePackingLib.SAPFuncs.ZChangeUserPassword ZChangeUserPassword) {
            StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordRequest inValue = new StandAlonePackingLib.SAPFuncs.ZChangeUserPasswordRequest();
            inValue.ZChangeUserPassword = ZChangeUserPassword;
            return ((StandAlonePackingLib.SAPFuncs.ZStandalonePacking)(this)).ZChangeUserPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StandAlonePackingLib.SAPFuncs.ZGetDgaUsersResponse1 StandAlonePackingLib.SAPFuncs.ZStandalonePacking.ZGetDgaUsers(StandAlonePackingLib.SAPFuncs.ZGetDgaUsersRequest request) {
            return base.Channel.ZGetDgaUsers(request);
        }
        
        public StandAlonePackingLib.SAPFuncs.ZGetDgaUsersResponse ZGetDgaUsers(StandAlonePackingLib.SAPFuncs.ZGetDgaUsers ZGetDgaUsers1) {
            StandAlonePackingLib.SAPFuncs.ZGetDgaUsersRequest inValue = new StandAlonePackingLib.SAPFuncs.ZGetDgaUsersRequest();
            inValue.ZGetDgaUsers = ZGetDgaUsers1;
            StandAlonePackingLib.SAPFuncs.ZGetDgaUsersResponse1 retVal = ((StandAlonePackingLib.SAPFuncs.ZStandalonePacking)(this)).ZGetDgaUsers(inValue);
            return retVal.ZGetDgaUsersResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZGetDgaUsersResponse1> StandAlonePackingLib.SAPFuncs.ZStandalonePacking.ZGetDgaUsersAsync(StandAlonePackingLib.SAPFuncs.ZGetDgaUsersRequest request) {
            return base.Channel.ZGetDgaUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZGetDgaUsersResponse1> ZGetDgaUsersAsync(StandAlonePackingLib.SAPFuncs.ZGetDgaUsers ZGetDgaUsers) {
            StandAlonePackingLib.SAPFuncs.ZGetDgaUsersRequest inValue = new StandAlonePackingLib.SAPFuncs.ZGetDgaUsersRequest();
            inValue.ZGetDgaUsers = ZGetDgaUsers;
            return ((StandAlonePackingLib.SAPFuncs.ZStandalonePacking)(this)).ZGetDgaUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsResponse1 StandAlonePackingLib.SAPFuncs.ZStandalonePacking.ZGetFinishedGoodMaterials(StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsRequest request) {
            return base.Channel.ZGetFinishedGoodMaterials(request);
        }
        
        public StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsResponse ZGetFinishedGoodMaterials(StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterials ZGetFinishedGoodMaterials1) {
            StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsRequest inValue = new StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsRequest();
            inValue.ZGetFinishedGoodMaterials = ZGetFinishedGoodMaterials1;
            StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsResponse1 retVal = ((StandAlonePackingLib.SAPFuncs.ZStandalonePacking)(this)).ZGetFinishedGoodMaterials(inValue);
            return retVal.ZGetFinishedGoodMaterialsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsResponse1> StandAlonePackingLib.SAPFuncs.ZStandalonePacking.ZGetFinishedGoodMaterialsAsync(StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsRequest request) {
            return base.Channel.ZGetFinishedGoodMaterialsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsResponse1> ZGetFinishedGoodMaterialsAsync(StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterials ZGetFinishedGoodMaterials) {
            StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsRequest inValue = new StandAlonePackingLib.SAPFuncs.ZGetFinishedGoodMaterialsRequest();
            inValue.ZGetFinishedGoodMaterials = ZGetFinishedGoodMaterials;
            return ((StandAlonePackingLib.SAPFuncs.ZStandalonePacking)(this)).ZGetFinishedGoodMaterialsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersResponse1 StandAlonePackingLib.SAPFuncs.ZStandalonePacking.ZGetProductionOrders(StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersRequest request) {
            return base.Channel.ZGetProductionOrders(request);
        }
        
        public StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersResponse ZGetProductionOrders(StandAlonePackingLib.SAPFuncs.ZGetProductionOrders ZGetProductionOrders1) {
            StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersRequest inValue = new StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersRequest();
            inValue.ZGetProductionOrders = ZGetProductionOrders1;
            StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersResponse1 retVal = ((StandAlonePackingLib.SAPFuncs.ZStandalonePacking)(this)).ZGetProductionOrders(inValue);
            return retVal.ZGetProductionOrdersResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersResponse1> StandAlonePackingLib.SAPFuncs.ZStandalonePacking.ZGetProductionOrdersAsync(StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersRequest request) {
            return base.Channel.ZGetProductionOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersResponse1> ZGetProductionOrdersAsync(StandAlonePackingLib.SAPFuncs.ZGetProductionOrders ZGetProductionOrders) {
            StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersRequest inValue = new StandAlonePackingLib.SAPFuncs.ZGetProductionOrdersRequest();
            inValue.ZGetProductionOrders = ZGetProductionOrders;
            return ((StandAlonePackingLib.SAPFuncs.ZStandalonePacking)(this)).ZGetProductionOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StandAlonePackingLib.SAPFuncs.ZGetSystemInfoResponse1 StandAlonePackingLib.SAPFuncs.ZStandalonePacking.ZGetSystemInfo(StandAlonePackingLib.SAPFuncs.ZGetSystemInfoRequest request) {
            return base.Channel.ZGetSystemInfo(request);
        }
        
        public StandAlonePackingLib.SAPFuncs.ZGetSystemInfoResponse ZGetSystemInfo(StandAlonePackingLib.SAPFuncs.ZGetSystemInfo ZGetSystemInfo1) {
            StandAlonePackingLib.SAPFuncs.ZGetSystemInfoRequest inValue = new StandAlonePackingLib.SAPFuncs.ZGetSystemInfoRequest();
            inValue.ZGetSystemInfo = ZGetSystemInfo1;
            StandAlonePackingLib.SAPFuncs.ZGetSystemInfoResponse1 retVal = ((StandAlonePackingLib.SAPFuncs.ZStandalonePacking)(this)).ZGetSystemInfo(inValue);
            return retVal.ZGetSystemInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZGetSystemInfoResponse1> StandAlonePackingLib.SAPFuncs.ZStandalonePacking.ZGetSystemInfoAsync(StandAlonePackingLib.SAPFuncs.ZGetSystemInfoRequest request) {
            return base.Channel.ZGetSystemInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZGetSystemInfoResponse1> ZGetSystemInfoAsync(StandAlonePackingLib.SAPFuncs.ZGetSystemInfo ZGetSystemInfo) {
            StandAlonePackingLib.SAPFuncs.ZGetSystemInfoRequest inValue = new StandAlonePackingLib.SAPFuncs.ZGetSystemInfoRequest();
            inValue.ZGetSystemInfo = ZGetSystemInfo;
            return ((StandAlonePackingLib.SAPFuncs.ZStandalonePacking)(this)).ZGetSystemInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StandAlonePackingLib.SAPFuncs.ZReceiptCartonsResponse1 StandAlonePackingLib.SAPFuncs.ZStandalonePacking.ZReceiptCartons(StandAlonePackingLib.SAPFuncs.ZReceiptCartonsRequest request) {
            return base.Channel.ZReceiptCartons(request);
        }
        
        public StandAlonePackingLib.SAPFuncs.ZReceiptCartonsResponse ZReceiptCartons(StandAlonePackingLib.SAPFuncs.ZReceiptCartons ZReceiptCartons1) {
            StandAlonePackingLib.SAPFuncs.ZReceiptCartonsRequest inValue = new StandAlonePackingLib.SAPFuncs.ZReceiptCartonsRequest();
            inValue.ZReceiptCartons = ZReceiptCartons1;
            StandAlonePackingLib.SAPFuncs.ZReceiptCartonsResponse1 retVal = ((StandAlonePackingLib.SAPFuncs.ZStandalonePacking)(this)).ZReceiptCartons(inValue);
            return retVal.ZReceiptCartonsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZReceiptCartonsResponse1> StandAlonePackingLib.SAPFuncs.ZStandalonePacking.ZReceiptCartonsAsync(StandAlonePackingLib.SAPFuncs.ZReceiptCartonsRequest request) {
            return base.Channel.ZReceiptCartonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandAlonePackingLib.SAPFuncs.ZReceiptCartonsResponse1> ZReceiptCartonsAsync(StandAlonePackingLib.SAPFuncs.ZReceiptCartons ZReceiptCartons) {
            StandAlonePackingLib.SAPFuncs.ZReceiptCartonsRequest inValue = new StandAlonePackingLib.SAPFuncs.ZReceiptCartonsRequest();
            inValue.ZReceiptCartons = ZReceiptCartons;
            return ((StandAlonePackingLib.SAPFuncs.ZStandalonePacking)(this)).ZReceiptCartonsAsync(inValue);
        }
    }
}
